part C:
  - name: duolingo
    expected_category: Education
    expected_folder: Education
  
  - name : jioaicloud
    expected_category: Productivity
    expected_folder: Productivity
    
     
  - name: Coursera
    expected_category: Education
    expected_folder: Education
   
  - name: Khan Academy
    expected_category: Education
    expected_folder: Education
    
  - name : sunoai
    expected_category: Productivity
    expected_folder: Productivity
    
  - name: elevenlabs
    expected_category: Productivity
    expected_folder: Productivity
   
  - name: perplexityai
    expected_category: Education
    expected_folder: Education
    
  - name : lovable
    expected_category: Productivity
    expected_folder: Productivity

  - name : chess.com
    expected_category: Games
    expected_folder: Games

  
